<style>
      .popup {
        display: none;
      }
      .accept {
        display: none;
      }
      #draggable {
        display: grid;
      }
    </style>
    <noscript>
      <style>
        .popup {
          display: flex;
        }
        .accept {
          display: block;
        }
        #draggable {
          display: none;
        }
      </style>
    </noscript>

    <link
      rel="stylesheet"
      href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css"
    />
  </head>

  <body>
    <div class="popup">
      Jeśli to widzisz, twój JavaScript jest wyłączony. Proszę włącz go by mieć
      pewność, że strona działała poprawnie.
      <input
        type="button"
        class="accept"
        value="OK"
        onclick="this.parentNode.style.display = 'none';"
      />
    </div>

    <script>
      window.onload = async function () {
        var popup = document.querySelector(".popup");
        popup.parentNode.removeChild(popup);
      };
    </script>

    <div id="draggable" class="ui-widget-content" title="Draggable">
      <div class="social1">
        <a href="https://github.com/fist-it" target="_blank">
          <img
            height="50"
            width="50"
            alt="github logo"
            src="./static/resource/svg/github-mark.svg"
          />
        </a>
      </div>
      <div class="social2">
        <a
          href="https://www.linkedin.com/in/franciszek-fabiński-a2688b233/"
          target="_blank"
          ><img
            height="50"
            width="50"
            alt="linkedin logo"
            src="./static/resource/svg/LinkedIn_icon.svg"
        /></a>
      </div>
      <div class="social3">
        <a href="mailto:fist_it@protonmail.com"
          ><img
            height="50"
            width="50"
            alt="protonmail logo"
            src="./static/resource/svg/proton-mail-seeklogo.com.svg"
        /></a>
      </div>
      <div class="social4">
        <a href="https://gitlab.com/fist-it"
          ><img
            height="50"
            width="50"
            alt="gitlab logo"
            src="./static/resource/svg/gitlab_logo.svg"
        /></a>
      </div>
    </div>

    <div class="layout">
      <header id="top"><a href="/">Strona główna</a></header>

      <nav>
        <ul>
          <li>
            <div class="dropdown">
              <button class="dropbtn"><b>Koty</b></button>
              <div class="dropdown-content">
                <a href="/cats">Wstęp</a>
                <a href="/cats/uni">Uni</a>
                <a href="/cats/panko">Panko</a>
                <a href="/cats/melonandfin">Melon i Fin</a>
                <a href="/cats/galeria">Galeria kotów</a>
              </div>
            </div>
          </li>
          <li>
            <a href="/translapl"><b>Transformata Laplace'a</b></a>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
          <li>
            <a href="#confirmationContainer">Zgłoś błąd</a>
          </li>
        </ul>
      </nav>
      <footer id="confirmationContainer">
        <p>
          Strona stworzona przez:
          <a href="mailto:s197797@student.pg.edu.pl">Franciszek Fabiński</a>
        </p>
        <img
          src="./static/resource/svg/Ficon.svg"
          alt="F-icon"
          width="50"
          height="50"
        />
        <form id="bugForm" method="get" action="odbierz.php">
          Jeśli napotkałeś/aś jakieś problemy na stronie, proszę zgłoś je tutaj:
          <br />
          <br />
          <textarea id="txtbug" maxlength="200"></textarea>
          <input type="submit" value="Wyślij" />
        </form>

        <div id="confirmationMessage"></div>
        <a href="#top">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 12h-2v2H9v-2H7l5-5 5 5z"
            />
          </svg>
        </a>
      </footer>